language: java
jdk: openjdk14
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: script
  script: |-
    ./gradlew publishPlugins publish
              -Dgradle.publish.key=$GRADLE_PUBLISH_KEY
              -Dgradle.publish.secret=$GRADLE_PUBLISH_SECRET
              -Dsigning.keyId=$SIGNING_KEY_ID
              -Dsigning.password=
              -Dsigning.secretKeyRingFile=key.gpg
              -Dsonatype.username=$SONATYPE_USER
              -Dsonatype.password=$SONATYPE_PASSWORD
              -Dmeta.version=$TRAVIS_TAG
  skip_cleanup: true
  on:
    tags: true
before_deploy:
- openssl aes-256-cbc -K $encrypted_2e6b62dd1b86_key -iv $encrypted_2e6b62dd1b86_iv
  -in key.gpg.enc -out key.gpg -d
env:
  global:
  - secure: pFH72irehBtobcaO9FqCWCaOVuSSrVaK/VEC4Y1MR5gxRadhy/eyYE38yQMitRmfiXFNBatrCymfcYZTBWG0SUbKgEVK95rv957gF9rPK51OkRhHW9vrqQZLpSgUICe35fwaX3ctm0MCJb0lleNdwwXOQZ9zkR/bBvhIdmSCt/4E4QXQlu7rR7xFi6bOqGUxOLtaWTPGyuvcMY+D7Z3+Ij0txfdo8VD4ioumNjtr/4mWrevDi63qs6qEtRH33laSIO732qyL5H01ZWZnHyY8DiQvyPoHoIgbQw/2LJUISHtLB1NFX2yyahFc9qI8Zpf2ur9UV2Y2l2baNVKH37w1OgxXPQkqVqSUmor9Hwfj3mBvTxAWTD0VNHbkPOuJxXGXMGCH+pm0eSuq46qJtgX9a1MJTzkysSEwcd0IWyKEi4Bge40iIXfa641cRBr3ipemmX8bTFJ/MmyVOr4jpQQM/qvtEC2pBT9THKpFPe68QHDgtsJpqrIjO4O/q+ZmudeSZtjFj51qeHd8kQF8mCyb1q153+n5HX9Yfbes4NgGvYHw0CUA94a4NgzDoDGxeIlt6ltvUTOfyg1VOFNqOJQ2C1NradEIzxIlZULH/mfukyztpMzb1IYMTqgqmcLzrvznwq9uFWgt2RSgP6jKFlF57xMtDyDc0lfG5Y6IrCQwu4w=
  - secure: MKKy6Vh/qfodHs8jjm4LhZRqq2//6LFEztjfH42RzrOeDU3rAy579XSK+lua3RTGXmj4Cf39oZiMUdORYfYuw/M5H+9b8WYGO2nbeEGmi9W8+/5YgP67Xdq6Fqghln5/Xei2rdbTgfV/g/A4GrC06YeJAhb+8K/eAFQux4wRYJzblETsubPCjAZxEovqd3w4ZOHcMxnwHNtml2eVUF0w5sNJIfLdq9vnK+nWsFufEtdfJQFODO9T4gMBr/rMF2ZD0p8D0lNE4pmCfQqrH/ryPh+Adt7Bq3iVIEl45u6e9T3O28NcFgPDyecF8zOIFzrccEsBRcIhMnhqkpssbMJqHK8SA1BZqqZQui4sAgRfbBN2BEoPA3v3ASmzBPVwCYS0WzeNetLbTc1Wwn339ZKqzcd8zDHAocYWaGibbEy7no4PFk7UgC4r1tOiWeeSuaVe1EiHDWe9H5PiyBPqGu7ZEEFrlAPXmkKjraMKTCQutjeG5XgTuK8RbGMXpqnNDVtfjl05wHArOOOsMsNTVSinzYyILURKpH/8fiOgWP6j4PQQ0TAK0tYU2K/VPzPspYT+YOgixzc9+oIsu+hO3drDWmQM1+zEVqtgJObNlzWzwcbCfwqlToTEbrSB9NSMQ13CKDSLFM+prE7xFgClwitXbbVfMM8ceyhl7s85f4kcKgM=
  - secure: jNqNIymcre4hKc20jXnhXyQNiIdaP+NA/tMYPl+gMVhJ4gxQ/brVQ4l4LSAJC2VMg8xQOjG3agQfR1rQSArG6Azx2q6Mnq8ZV2M3L+BoPIRFXXpVD2qThCf0RsEhQfJH0t8oXIctdeU/B3bPeY9qqLutFz6mPSLBYkTvjD4+AOHq+ei3ixv3dEcXKI1kdot3xbERvmTTc5ig6ygPOUFY0vfZelNfEfv+z9eDt4tMHEDR5lPxXNZW5rbCm2RuXP/08iJuxCKjYSk9qXjQ63hQE+pqpU55un94X8LAU7OPwH2AjwtVDYnCs22fegmRZahDeGhufwpxd7qYgaeqOXjVgjUsmBKDJQNfBpyoKEoOysUwPDQsiaDIEcytYZINNhYMsGh6QbYymHYxrB+ILVPAqPIWRVjOuXug0W5lE5Y4QSwnClbB/vxilQJBE+jDHXbqqIj1Mr422+D4ebHISmyknhOGEloucNc1X7QITvKAxAQh0/dTtprdGrgCdCx1TPfm4bAgzdbY0ELa+AYgSocGN+XGcbKD0OBkECjw2/kGWP+bn8EXYMMxqk2yuX668ZdmNnzw58C2iQI0NAh/21s5MtYDIDiY13NqsSLOCm5mqJd+an/lUz7E4NwBaXYU7edIOh9k4VnoaTmSzezGlaCBeMbyVnqrkyGld4T01TbIXPk=
